# Generated by Django 3.2.12 on 2022-11-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_employee_birthdate_employee_birthtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('coursePrice', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.course')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
            },
            bases=('blog.course',),
        ),
    ]
